### ISSUE TITLE
StackedConfig object with only string key accessibility for config files values

### ISSUE THREAD

**Issue by paulRbr** [lbriais/stacked_config#6]
StackedConfig v1 used to parse config files and merge everything in a `StackedConfig` object with values accessible via symbol keys.

config_file.yml

``` yml
hello: "world"
```

app.rb

``` ruby
# StackedConfig v1
...
config[:hello] == "world"
...
```

---

WIth StackedConfig v2 this is broken and the configuration loaded via a config file is set with a `String` key. 

config_file.yml

``` yml
hello: "world"
```

app.rb

``` ruby
# StackedConfig v2
...
config[:hello] == nil
config["hello"] == "world"
...
```

**Comment by lbriais** [comment]
Hello Paul,

This is absolutely true and the actual reason why the major version has been bumped to 2.x (according to [semantic versioning](http://semver.org/)). This is described in the [super_stack documentation](https://github.com/lbriais/stacked_config#between-version-1x-and-2x) along with how to work-around.

The real change was introduced in the `super_stack` gem () which version was bumped to 1.x for the same reason (see the [warning in that paragraph](https://github.com/lbriais/super_stack#create-a-manager)). This is the reason as well why `easy_app_helper` has been bumped to 4.x...

**Nevertheless you may be interested in knowing that there is a compatibility mode available to mimic old behaviour.**

Thus users of `easy_app_helper` can either choose to:
- stay on the old branch 3.x (tell me you use the pessimistic `~>` operator when specifying your dependencies ;-) )
- move to the new 4.x branch of easy_app_helper. For this you can either use the compatibility mode (this is as simple as requiring `easy_app_helper/old` instead of `easy_app_helper`) or migrate your configuration files to the [new requirements](https://github.com/lbriais/stacked_config#between-version-1x-and-2x) (which as not always possible is the reason of the compatibility mode...).

**Comment by paulRbr** [comment]
Wow. I didn't RTFM. Thanks a lot for the heads up.

I guess you are right I should just use symbol keys in my yaml definition!

Again thanks :).

Em 01/08/2016 13:41, "L.Briais" notifications@github.com escreveu:
